### PR TITLE
Enum enhancements

### PR DESCRIPTION
**Pull request by joeflack4**
@cmungall 

As of 2022/04/08, this is in the very early stages. No current ETA for when this will be done.

### CODE REVIEW

**Comment by cmungall** [comment]
hi @joeflack4 - this is why it's good to make PRs :-)

There are 356 changes on this branch, and many conflicts

I think it will be easiest for you to start a fresh branch/PR - on that branch, *only* make changes to the metamodel yaml files (likely only meta.yaml). Don't check in any derived files. use our standard github workflow for syncing with main

**Comment by joeflack4** [comment]
@cmungall Blame Harold! (@hsolbrig sorry xD).

We just started this branch like 30 minutes before the LinkML presentation. I think the branch that Harold checked out from must have been old or not master. I only saw him add one file and edit a couple others. He did run some tests. Other than that I'm not sure what happened there. @hsolbrig Want to start a fresh branch off of master and repeat the work from the last commit?

**Comment by sierra-moxon** [comment]
@joeflack4 @hsolbrig  - should we close this one?  I'm pushing to get all PRs merged in today. :)

**Comment by joeflack4** [comment]
@sierra-moxon Totally understandable, I'll go ahead and close. Most of these commits are accidental, I think. We only put like 15 minutes of work into this; we can easily replicate in the future, should we need.

**Pull request closed without merging**
